[workspace]
members = [
	"HGE",
	"examples/*",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "1.0.0"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
Hconfig = { path = "../../rust/Hconfig" }
Htrace = { path = "../../rust/Htrace" }
